version = 1

[[analyzers]]
name = "go"
enabled = true

[analyzers.meta]
import_root = "github.com/CyberdyneHQ/<repository-name>"

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "python"
enabled = true

[analyzers.meta]
runtime_version = "3.x.x"

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "black"
enabled = true
